[package]
name = "ncrypt0r"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libaes = "0.6.1"
sha2 = "0.9.8"
walkdir = "2.3.2"
structopt = "0.3.25"
ansi_term = "0.12.1"